import matplotlib.pyplot as plot
from InputOutput import readRawData

datapointsSifein1 = readRawData("Röntgen/221109_Sifein_Peak1.txt")
datapointsSifein2 = readRawData("Röntgen/221109_Sifein_Peak2.txt")
datapointsSifein3 = readRawData("Röntgen/221109_Sifein_Peak3.txt")
datapointsSigrob1 = readRawData("Röntgen/221109_Sigrob_Peak1.txt")
datapointsSigrob2 = readRawData("Röntgen/221109_Sigrob_Peak2.txt")
datapointsSigrob3 = readRawData("Röntgen/221109_Sigrob_Peak3.txt")
datapointsUnbekannt1 = readRawData("Röntgen/221109_unbekanntesSalz.txt")
datapointsUnbekannt2 = readRawData("Röntgen/221110_unbekanntesSalz.txt")

plot.plot(*zip(*datapointsSifein1), label='Silizium fein, Winkel 27-30 Grad', color = "darkgreen")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()
plot.plot(*zip(*datapointsSifein2), label='Silizium fein, Winkel 46-49 Grad', color = "forestgreen")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()
plot.plot(*zip(*datapointsSifein3), label='Silizium fein, Winkel 55-58 Grad', color = "limegreen")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()
plot.plot(*zip(*datapointsSigrob1), label='Silizium grob, Winkel 55-58 Grad', color = "darkred")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()
plot.plot(*zip(*datapointsSigrob2), label='Silizium grob, Winkel 55-58 Grad', color = "firebrick")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()
plot.plot(*zip(*datapointsSigrob3), label='Silizium grob, Winkel 55-58 Grad', color = "indianred")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()
plot.plot(*zip(*datapointsUnbekannt1), label='unbekanntes erstes Salz, Winkel 10-120 Grad', color = "goldenrod")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()
plot.plot(*zip(*datapointsUnbekannt2), label='unbekanntes zweites Salz, Winkel 10-120 Grad', color = "darkgoldenrod")
plot.legend(loc="upper left")
plot.xlabel("Winkel")
plot.ylabel("Intensität")
# plot.savefig("transparenteKalibrierung", transparent = True)
plot.show()